sudo: false
language: 'elixir'
elixir:
  - '1.7'
  - '1.8.1'
otp_release:
  - '20.3'
  - '21.2.6'
git:
  quiet: true
env:
  - 'PLT_DIR=$HOME/.plt'
cache:
  directories:
    - '_build'
    - 'deps'
    - '$PLT_DIR'
before_script:
  - 'mkdir -p $PLT_DIR'
  - 'mix deps.get --force'
  - 'mix deps.compile --force'
  - 'mix compile --force'
  - 'travis_wait 30 mix dialyzer --plt'
  - 'MIX_ENV=test mix deps.get --force'
  - 'MIX_ENV=test mix deps.compile --force'
script:
  - 'mix credo --strict --all'
  - 'MIX_ENV=test mix compile --force --warnings-as-errors'
  - 'MIX_ENV=test mix format --check-formatted --dry-run'
  - 'mix purge.db'
  - 'MIX_ENV=test mix coveralls.json --no-start'
after_success:
  - 'bash <(curl -s https://codecov.io/bash)'
  - 'mix inch.report'
notifications:
  email:
    - 'randy@heroictek.com'
